language: cpp
os:
  - osx
env:
  - CONFIG=Release
  - CONFIG=Debug
install:
      brew update
  &&  brew install qt5
  && chmod -R 755 /usr/local/opt/qt5/*
script:
      cd ./src
  &&  /usr/local/opt/qt5/bin/qmake QSyncThingTray.pro
  &&  make
